Repository asam-ev/qc-framework, pull requests merged in 2024-10, with the labels that each got.

#195 Solves #194 - Root module `runtime`
  .github/workflows/build-on-change-linux-bare.yaml
  .github/workflows/build-on-change-linux-docker.yaml
  .github/workflows/build-on-change-windows.yaml
  INSTALL.md
  doc/manual/demo_pipeline.md
  doc/manual/file_formats.md
  doc/manual/manifest_file.md
  doc/manual/python_qc_framework.md
  doc/manual/using_the_framework.md
  docker/Dockerfile.linux
  docker/test_runtime.sh
  qc_framework/poetry.lock
  qc_framework/pyproject.toml
  qc_framework/qc_framework/__init__.py
  qc_framework/qc_framework/__main__.py
  qc_framework/qc_framework/runtime/__init__.py
  qc_framework/qc_framework/runtime/models.py
  qc_framework/qc_framework/runtime/runtime.py
  qc_framework/tests/__init__.py
  qc_framework/tests/test_data/3step_config.xml
  qc_framework/tests/test_data/linux/demo_checker_bundle_manifest.json
  qc_framework/tests/test_data/linux/framework_manifest.json
  qc_framework/tests/test_data/linux/result_pooling_manifest.json
  qc_framework/tests/test_data/linux/text_report_manifest.json
  qc_framework/tests/test_data/windows/demo_checker_bundle_manifest.json
  qc_framework/tests/test_data/windows/framework_manifest.json
  qc_framework/tests/test_data/windows/result_pooling_manifest.json
  qc_framework/tests/test_data/windows/text_report_manifest.json
  qc_framework/tests/test_runtime.py
  runtime/runtime/__init__.py
  runtime/tests/__init__.py
Labels: isState:New, isState:ForCCBReview

#198 Prepare to release v1.0.0-rc.1
  .github/workflows/build-and-push-demo-pipeline.yaml
  .github/workflows/build-on-change-linux-bare.yaml
  .github/workflows/build-on-change-linux-docker.yaml
  .github/workflows/build-on-change-windows.yaml
  .github/workflows/windows-manifest/framework.json
  .github/workflows/windows-manifest/odr.json
  .github/workflows/windows-manifest/osc.json
  .github/workflows/windows-manifest/otx.json
  .github/workflows/windows-manifest/result_pooling.json
  .github/workflows/windows-manifest/text_report.json
  INSTALL.md
  README.md
  doc/changelog.txt
  doc/manual/demo_pipeline.md
  doc/manual/esmini_viewer_plugin.md
  doc/manual/python_qc_framework.md
  doc/manual/writing_user_defined_modules.md
  docker/Dockerfile.linux
  manifest_examples/windows/qc_opendrive.json
  manifest_examples/windows/qc_openscenarioxml.json
  manifest_examples/windows/qc_otx.json
  manifest_examples/windows/report_gui.json
  manifest_examples/windows/result_pooling.json
  manifest_examples/windows/text_report.json
  qc_framework/README.md
  qc_framework/poetry.lock
  qc_framework/pyproject.toml
  qc_framework/tests/test_data/windows/demo_checker_bundle_manifest.json
  qc_framework/tests/test_data/windows/result_pooling_manifest.json
  qc_framework/tests/test_data/windows/text_report_manifest.json
Labels: isState:ForCCBReview

#199 Simplify cpp checker bundle example and update cpp baselib
  examples/checker_bundle_example/src/main.cpp
  examples/checker_bundle_example/src/main.h
  include/common/result_format/c_checker_bundle.h
  include/common/result_format/c_issue.h
  qc_framework/tests/test_data/3step_config.xml
  src/common/src/result_format/c_checker_bundle.cpp
  src/common/src/result_format/c_issue.cpp
  test/function/examples/example_checker_bundle/files/DemoCheckerBundle.xqar
  test/function/examples/example_checker_bundle/files/DemoCheckerBundle_config.xml
  test/function/examples/example_checker_bundle/src/example_checker_bundle_tester.cpp
Labels: isState:ReadyForMerge
